import fs from "fs";
const s = fs.readFileSync("D:/server-official-site/or.js", "utf8");
const needle = 'l=[{name:"Eraze"';
const start = s.indexOf(needle);
if (start < 0) throw new Error("not found");
const sub = s.slice(start, start + 15000);
const end = sub.indexOf("}],m(\"div\",lp");
if (end < 0) throw new Error("end not found");
const arr = sub.slice(2, end + 1);
fs.writeFileSync("D:/server-official-site/.tools/team-snippet.txt", arr);
